# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adm123
    ports:
      - "5432:5432"
    volumes:
      - ./InitDb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  smtp:
    image: rnwood/smtp4dev:latest
    ports:
      - "3000:80"
      - "2525:25"
    
volumes:
  db_data: