apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  POSTGRES_DB: replace-me
  POSTGRES_USER: replace-me
  POSTGRES_PASSWORD: replace-me
  CONNECTION_STRING: replace-me
  JWT_KEY: replace-me
