apiVersion: v1
kind: Service
metadata:
  name: svc-gerenciamento-db
spec:
  selector:
    app: gerenciamento-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  