@GerenciamentoMecanicaSistema_HostAddress = http://localhost:32776

### CREATE ### ADICIONAR RETORNO DO CLIENTE AO CRIAR
### Criar Cliente Felipe com CPF

POST {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/CreateCliente/
Content-Type: application/json

{
  "nome": "Felipe",
  "documento": "123.456.789-12",
  "celular": "(11) 91234-5678",
  "email": "felipe@gmail.com"
}

### Criar Cliente Rodrigo com CNPJ

POST {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/CreateCliente/
Content-Type: application/json

{
  "nome": "Rodrigo",
  "documento": "12.123.456/0001-15",
  "celular": "(14) 91234-5678",
  "email": "digao@gmail.com"
}

### Criar Cliente Editável com CNPJ

POST {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/CreateCliente/
Content-Type: application/json

{
  "nome": "Rebecca",
  "documento": "98765432100",
  "celular": "(18) 91918-1716",
  "email": "rebecca@gmail.com"
}

### READ
### Recebe Clientes

GET {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/GetClientes/
Accept: application/json

### Recebe Cliente de Documento 12345678912 (CPF)

GET {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/GetClienteByDocumento/12345678912
Accept: application/json

### Recebe Cliente de Documento 12123456000112 (CNPJ)

GET {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/GetClienteByDocumento/12123456000112
Accept: application/json

### UPDATE
### Atualiza Cliente de Documento 12345678912 (CPF)

PATCH {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/UpdateCliente/
Content-Type: application/json

{
  "nome": "Felps",
  "documento": "123.456.789-12",
  "celular": "(11) 91234-5678",
  "email": "felps@gmail.com"
}

### Atualiza Cliente de Documento 12123456000112 (CNPJ)

PATCH {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/UpdateCliente/
Content-Type: application/json

{
  "nome": "Digão",
  "documento": "12.123.456/0001-12",
  "celular": "(14) 91234-5678",
  "email": "digao@gmail.com"
}

### DELETE
### Deleta Cliente de Documento 12345678912 (CPF)

DELETE {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/DeleteCliente/12345678912
Accept: application/json

### Deleta Cliente de Documento 12123456000112 (CNPJ)

DELETE {{GerenciamentoMecanicaSistema_HostAddress}}/cliente/DeleteCliente/12123456000112
Accept: application/json
