apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: adm123
  CONNECTION_STRING: Host=svc-gerenciamento-db;Port=5432;Database=postgres;Username=postgres;Password=adm123
  JWT_KEY: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
